services:
  database:
    image: mariadb:latest
    container_name: ${PROJECT_NAME}_database_${PROJECT_ENV}
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_TCP_PORT: ${DATABASE_PORT}
    networks:
      - internal
    volumes:
      - strapi-database:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}

networks:
  internal:
    driver: bridge

volumes:
  strapi-database:
    name: ${PROJECT_NAME}_strapi-database_${PROJECT_ENV}
    driver: local